export default new Map<string, string>([
  ['language-name', 'English'],
  ['operation-addition', '{operand0} plus {operand1}'],
  ['operation-subtraction', '{operand0} minus {operand1}'],
  ['operation-multiplication', '{operand0} multiplied by {operand1}'],
  ['operation-division', '{operand0} divided by {operand1}'],
  ['operation-percent', '{operand1} percent of {operand0}'],
  ['label-clear-scores', 'Clear today\'s scores'],
  ['label-clear-records', 'Clear records'],
  ['title-daily-records', 'Today\'s records'],
  ['title-language', 'Language'],
  ['title-level', 'Level'],
  ['title-level-abbr', 'Lvl'],
  ['title-personal-best', 'Best'],
  ['title-settings', 'Settings'],
  ['text-about-scores', 'These scores will be cleared automatically by the end of the day. Try to beat your own records every day!'],
  ['text-clear-scores', 'Daily scores will be cleared automatically by the end of the day. But, clear them now if you want to start today over.'],
  ['text-clear-records', 'Use the records to assess your daily achievements. Clear them only if you\'d like to re-establish your personal records.'],
])
