export default new Map<string, string>([
  ['language-name', 'Español'],
  ['modality-visual', 'Visual'],
  ['modality-aural', 'Auditiva'],
  ['modality-shuffled', 'Aleatoria'],
  ['operation-addition', '{operand0} más {operand1}'],
  ['operation-subtraction', '{operand0} menos {operand1}'],
  ['operation-multiplication', '{operand0} multiplicado por {operand1}'],
  ['operation-division', '{operand0} dividido entre {operand1}'],
  ['operation-percent', '{operand1} porciento de {operand0}'],
  ['label-clear-scores', 'Borrar puntajes de hoy'],
  ['label-clear-records', 'Borrar récords'],
  ['title-daily-records', 'Puntajes de hoy'],
  ['title-language', 'Idioma'],
  ['title-modality', 'Modalidad'],
  ['title-level', 'Nivel'],
  ['title-level-abbr', 'Nvl'],
  ['title-personal-best', 'Récord'],
  ['title-settings', 'Configuración'],
  ['title-utterance-speed', 'Velocidad de expresión'],
  ['text-about-scores', 'Estos puntajes se borrarán automáticamente al final del día. ¡Trata de batir tus propios récords cada día!'],
  ['text-clear-scores', 'Los puntajes de hoy serán borrados automáticamente al final del día. Aunque si deseas recomenzar el día, bórralos ahora.'],
  ['text-clear-records', 'Usa los récords para comparar y evaluar a diario tu desempeño. Aunque si deseas re-establecer tu marca, bórralos ahora.'],
])
